In [116]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [117]:
names = ['Age','Gender','Job','Market']

dataset = pd.read_csv('data/WKW_marketingcampaign_event1.csv', names=names)

In [118]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [119]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])


In [120]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [121]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [122]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

TRAINING

In [123]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

TESTING

In [124]:
y_pred = classifier.predict(X_test)

EVALUATING

In [125]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[2 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 6]]
                   precision    recall  f1-score   support

Community Partner       0.67      0.67      0.67         3
 INVITED DELEGATE       0.00      0.00      0.00         1
       Influencer       0.00      0.00      0.00         1
               PP       0.00      0.00      0.00         1
 Social Media Ads       0.67      1.00      0.80         6

         accuracy                           0.67        12
        macro avg       0.27      0.33      0.29        12
     weighted avg       0.50      0.67      0.57        12



C:\Users\ihuda\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ihuda\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ihuda\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

PREDICT

In [128]:
"""
predict(Employee,Freelance,Student,Age,Gender)
Employee 0/1
Freelance 0/1
Student 0/1
Age int
Gender 0 = Female / 1 = Male
"""
input = [[1,0,0,19,1]]
input = scaler.transform(input)

In [129]:
result = classifier.predict(input)
print("Market : " + result)

['Market : Social Media Ads']
